import "./globals.css";

export const metadata = {
	title: "Trello clone",
	description: "Generated by Andre Nakashima",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
			<body>{children}</body>
		</html>
	);
}
